### PR TITLE
Update podspec to support tvOS

### PR DESCRIPTION
**Pull request by ThanhTurin**

### CODE REVIEW

**Comment by granoff** [comment]
Thanks for doing this. Would you also bump the version to `3.0.4` and push a tag that matches?

**Comment by ThanhTurin** [comment]
Thanks @granoff for your suggestion. I just added one commit to bump version to `3.0.4` and also tagged it. Would you take a look again!

**Comment by granoff** [comment]
Thanks @ThanhTurin  for the contribution!

**Comment by ThanhTurin** [comment]
Thanks @granoff. Confirmed `3.0.4` works on my project!

**Pull request merged**
